### ISSUE TITLE
Should target be set to 'web'

### ISSUE THREAD

**Issue by marknorgren** [luckymarmot/Paw-DigestAuthDynamicValue#1]
In the example target is set to node `target: 'node-webkit'`

To get my extension to run in Paw I had to set this to: `target: 'web'`

Is this wrong in the example - or am I missing something ?

https://github.com/luckymarmot/Paw-DigestAuthDynamicValue/blob/master/webpack.config.babel.js#L9

**Comment by JonathanMontane** [comment]
hi @mrkd, it seems that the `node-webkit` target is not super reliable, and switching to `web` should do the trick. Would you mind providing us with the error message you had? I failed to reproduce the issue.

I'll do a quick fix once I've identified if there's not a larger problem underneath.

**Comment by JonathanMontane** [comment]
fixed
